version: '3'

services:
  sync:
    build: ./sync
    container_name: Django
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - ./sync/:/usr/src/app/
    ports:
      - 7000:7000
  async:
    build: ./async
    container_name: Sanic
    command: python app.py
    volumes:
      - ./async/:/usr/src/app/
    ports:
      - 9000:9000